// List of materials for auto-suggestions
export const materialsList = [
  "C.Cable",
  "B.Cable",
  "Nayem",
  "Asp B/B",
  "Asp Radiator",
  "Asp Powder",
  "Zinc (pow)",
  "Zinc",
  "Gage Clean",
  "Gage N/C",
  "Alu Cable Shiny",
  "Alu Cable N/S",
  "Alu Rim",
  "Alu Beam Plate",
  "Alu Caps",
  "Alu Tense",
  "Steel 316 Turning",
  "Alu Radiator",
  "Alu Powder",
  "Alu Gidur",
  "A/C Radiator",
  "Alu Harik",
  "Steel-304",
  "Steel-316",
  "Steel NI 904",
  "Steel-(NI)",
  "Steel Gidur-201",
  "Lead",
  "Gage cutting pes",
  "Sign Bord",
  "Mill Finish (loose)",
  "Condesser block",
  "Telic Extrution",
  "Tagil Powder",
  "Lithu Sheet",
  "Foil Paper 2",
  "NI (10/90)",
  "Medical Foil",
  "Battery",
  "Hadid",
  "Alu Sharaded",
  "Mill Finish (block)",
  "Compressor",
  "AL Cable insulate",
  "Miltat Telon",
  "Silk",
  "Condensser Pipe",
  "Pepsi Block",
]
